version: '3.9'
services:
  spring:
    container_name: spring
    image: pinting/spring:1.0.0
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://db:5432/var/lib/postgresql/data
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - pinting-net
  db:
    container_name: db
    image: postgres
    pull_policy: never
    restart: always
    build: ./postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    networks:
      - pinting-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  pinting-net:
    driver: bridge


volumes:
  pgdata: {}
